/*

DROP TABLE IF EXISTS SETOR;  
CREATE TABLE SETOR (ID_Setor             INT          AUTO_INCREMENT PRIMARY KEY   
                   ,NM_Setor             VARCHAR(30)  NOT NULL);

*/

INSERT INTO SETOR (NM_Setor) VALUES ('CENTRO');
INSERT INTO SETOR (NM_Setor) VALUES ('ZONA NORTE');
INSERT INTO SETOR (NM_Setor) VALUES ('ZONA SUL');
INSERT INTO SETOR (NM_Setor) VALUES ('ZONA LESTE');
INSERT INTO SETOR (NM_Setor) VALUES ('ZONA OESTE');    